### ISSUE TITLE
"Fix a few variable reassignments" broke WDK build

### ISSUE THREAD

**Issue by ghost** [XhmikosR/notepad2-mod#89]
Running

```
build_wdk.bat build x64
```

on master returns this (trimmed)

<pre>
______________________________
[INFO] Visual Studio 2010 wasn't found, I will use WDK's compiler
______________________________

On branch: master
Hash:      55a39c7
Revision:  922

Styles.c
..\src\Notepad2.c(2874) : error C2143: syntax error : missing ';' before 'type'
..\src\Notepad2.c(2875) : error C2065: 'iNewPos' : undeclared identifier
..\src\Notepad2.c(5080) : error C2061: syntax error : identifier 'MsgNotify'
..\src\Notepad2.c(5080) : error C2059: syntax error : ';'
..\src\Notepad2.c(5080) : error C2059: syntax error : 'type'
NMAKE : fatal error U1077: 'C:\WinDDK\7600.16385.1\bin\x86\amd64\cl.exe' : return code '0x2'
Stop.

______________________________
[ERROR] Compilation failed!
______________________________

Press any key to continue . . .
</pre>

`git bisect` reveals this

```
b2e89111f9201f0205d5b2be13a1efe77f153075 is the first bad commit
commit b2e89111f9201f0205d5b2be13a1efe77f153075
Author: XhmikosR <xhmikosr@users.sourceforge.net>
Date:   Sun Jun 22 11:06:31 2014 +0300
Fix a few variable reassignments.
```

So b2e8911 is the culprit
